### ISSUE TITLE
如何根据是否小米系统选择性启动小米推送??

### ISSUE THREAD

**Issue by Ping5841** [cpunion/react-native-mipush#1]

**Comment by cpunion** [comment]
你可以看一下MiPushApplication，写一个自己的Application，根据系统执行不同启动逻辑。

然后在JS里面判断是否小米系统，来决定是否要启动push。

以后有时间可以考虑提供干净的切换。

**Comment by Ping5841** [comment]
好的 谢谢

**Comment by Ping5841** [comment]
@cpunion 你好,请问我这边能收到推送,但是调不起APP ,在UI界面,接收新消息,也不执行监听代码,是怎么回事??

**Comment by cpunion** [comment]
推送打开APP是小米的后台参数，只要能显示就应该能打开应用，你在推送工具里面选一下。

**Comment by Ping5841** [comment]
我已经在推送工具那里选择了打开应用,但是点击手机端的推送消息并没有反应

**Comment by cpunion** [comment]
检查一下两端的包名对不对，也要注意logcat日志。push设置成功了你才能收到消息，点击消息不能弹出界面和react这部分无关，包名不对的可能性大。
