### ISSUE TITLE
rn版本0.32以上怎么更新MainActivity

### ISSUE THREAD

**Issue by yulianger** [cpunion/react-native-mipush#2]
rn版本0.32以上怎么更新MainActivity.java ？还是改MainApplication.java？

**Comment by cpunion** [comment]
```
public class MainApplication extends MiPushApplication implements ReactApplication {
// ...
```

其他代码基本不变。

**Comment by yulianger** [comment]
// ...
public class MainActivity extends ReactActivity {
    private MiPushPackage mMiPushPackage;            <---- 添加

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        mMiPushPackage = new MiPushPackage(this);    <---- 添加
        super.onCreate(savedInstanceState);
    }

    @Override
    protected void onNewIntent(Intent intent) {      <---- 添加这个方法
        super.onNewIntent(intent);
        setIntent(intent);
        mMiPushPackage.onIntent(intent);
    }

    // ...
    @Override
    protected List<ReactPackage> getPackages() {
        return Arrays.asList(
            new MainReactPackage(),
            mMiPushPackage,         // <------ 修改自动生成的 new MiPushPackage
    // ...   
   这里的代码段呢？

**Comment by cpunion** [comment]
给一段我在用的，可能也并不是很好：

MainApplication.java
```java
public class MainApplication extends MiPushApplication implements ReactApplication {
  private MiPushPackage mMiPushPackage = new MiPushPackage();

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    protected boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.asList(
        new MainReactPackage(),
        mMiPushPackage
      );
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
      return mReactNativeHost;
  }

  public MiPushPackage getMiPushPackage() {
    return mMiPushPackage;
  }
}
```

MainActivity.java:

```java
@Override
    public void onNewIntent(Intent intent) {
        super.onNewIntent(intent);

        setIntent(intent);

        (MainApplication)getApplication().getMiPushPackage().onIntent(intent);
    }
```

**Comment by yulianger** [comment]
AndroidManafest.xml 配置文件中的
<application
      android:name="com.xiaomi.push.reactnative.MiPushApplication"  <----- 这里

还是否需要？

**Comment by cpunion** [comment]
这里当然是改成你的MainApplication，要不然怎么用上呢？
