### ISSUE TITLE
请问

### ISSUE THREAD

**Issue by ArvoGuo** [cpunion/react-native-mipush#4]
我自己接mipush 遇到了问题， 

```js
 onReceiveRegisterResultcommand={register}, resultCode={0}, reason={null}, category={null}, commandArguments={[FlOu+41fmYVvD1plYkpPe24UmDPiHNBmWNCrRlDaXj0=]}
```

这个返回都是success  但手机始终没收到通知， 请问是否遇到过？

**Comment by cpunion** [comment]
我最近没有测试过，早期偶尔出现这种情况，但是并不稳定重现，猜测可能是小米SDK或后端环境问题，这个包里面也没有继续升级。如果一次都没有成功过，建议通过小米的测试工具和日志排查一下。设备注册成功以后，后端应该能看到设备；推送消息以后，logcat 应该有日志。

**Comment by ArvoGuo** [comment]
感谢 已有眉目
